# Estágio 1: Build da Aplicação
FROM eclipse-temurin:17-jdk-focal as build
WORKDIR /app

# Copia o arquivo de configuração do Maven
COPY pom.xml ./

# Copia o código-fonte
COPY src ./src

# Build do projeto (sem testes)
RUN --mount=type=cache,target=/root/.m2 mvn clean package -DskipTests

# Estágio 2: Criação da Imagem de Execução
FROM eclipse-temurin:17-jre-focal
WORKDIR /app
EXPOSE 8080

# Copia o .jar gerado
COPY --from=build /app/target/*.jar app.jar

# Define variáveis de ambiente para MongoDB (opcional, pode ser sobrescrito)
ENV SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/sistemadepadaria

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]
